services:
  nestjs-app:
    container_name: nestjs-app
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "npm install && npm run start:dev"
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: nest-postgres
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  prisma-studio:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio
    depends_on:
      - postgres
    ports:
      - '5555:5555' # Expose Prisma Studio on host port 5555

volumes:
  postgres-data:
